name: BOOTCAMP26- Backend deployment
run-name: Backend deployment triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - deployment
    paths:
      - backend/**
      - .github/workflows/backend.yaml

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        defaults:
          run:
            working-directory: backend
        steps:
          - name: Checkout the code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: 11
          - name: Cache Maven packages
            uses: actions/cache@v1
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2    
          - name: Login to GitHub Container Registry
            run: docker login --username ${{secrets.GHCR_USERNAME}} --password ${{secrets.GHCR_PAT}} ghcr.io 
          - name: Build Docker Image
            run:  docker build . --tag ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-backend:latest
          - name:  Push Docker Image to GHCR
            run: docker push ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-backend:latest          
    deploy:
      needs: build
      runs-on: ubuntu-latest
      timeout-minutes: 10
      defaults:
        run:
          working-directory: backend
      steps:
        - name: Create a file to store AWS key-pair
          run: touch aws-key-pair.txt
        - name: Copy the key-pair from secrets to the file
          run: |
           echo "${{ secrets.AWS_KEY_PAIR }}" > aws-key-pair.txt
        - name: Change permession for the file
          run: chmod 400 aws-key-pair.txt
        - name: Connect to ec2 instance
          run: ssh -i aws-key-pair.txt ubuntu@15.206.237.21
        - name: Checkout the code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Pull image from GHCR
          run: docker pull ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-backend:latest
        - name: Run Docker Container
          run: |
           docker run -p 8090:8090 -d --name bootcamp26-backend_Container \
           -e SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}} \
           -e SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}} \
           -e SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}} \
           ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-backend:latest


            

            
        
