name: BOOTCAMP122 - Frontend deployment 
run-name: Frontend deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - "deployment"
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
        run:
          working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps
      - name: Build application
        run: |
         npm run build
         cp -r public/assets dist/

      - name: Login to GitHub Container Registry
        run: docker login --username ${{secrets.GHCR_USERNAME}} --password ${{secrets.GHCR_PAT}} ghcr.io 
      - name: Build Docker Image
        run:  docker build . --tag ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-frontend:latest
      - name:  Push Docker Image to GHCR
        run: docker push ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-frontend:latest          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
        run:
          working-directory: frontend
          shell: bash
    steps:
        - name: Checkout the code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Copy the key-pair from secrets to the file
          run: |
           echo "${{ secrets.AWS_KEY_PAIR }}" > aws-key-pair.pem
        - name: Change permession for the file
          run: chmod 400 aws-key-pair.pem
        - name: executing remote ssh commands using ssh key
          run: |
           ssh -o StrictHostKeyChecking=no -i aws-key-pair.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_FRONTEND }} \
           "docker login --username ${{secrets.GHCR_USERNAME}} --password ${{secrets.GHCR_PAT}} ghcr.io &&
           docker pull ghcr.io/${{secrets.GHCR_USERNAME}}/bootcamp26-frontend:latest &&
           if docker inspect bootcamp26-frontend_Container &> /dev/null; then
              docker stop bootcamp26-frontend_Container || true
              docker rm bootcamp26-frontend_Container || true
           fi &&
           docker run -p 80:80 -d --name bootcamp26-frontend_Container \
              ghcr.io/pranjal-mukherjee/bootcamp26-frontend:latest"
